---
- name: Add InfluxDB yum repository
  yum_repository:
    name: influxdata
    description: InfluxData Repository
    baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
    gpgcheck: true
    gpgkey: https://repos.influxdata.com/influxdata-archive_compat.key
    enabled: true
  become: true

- name: Install influxdb2
  package:
    name: influxdb2
    state: present
  become: true
  notify: restart influxdb
