# OpenRVDAS inventory file
# Add your target hosts below.
#
# Examples:
#   vessel01 ansible_host=192.168.1.10 ansible_user=admin
#   vessel02 ansible_host=192.168.1.11 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/vessel02.pem
#
# For a local install (same machine running Ansible):
#   localhost ansible_connection=local
#
# Group hosts by vessel or environment:
#   [research_vessels]
#   nbp ansible_host=192.168.1.10
#
#   [test]
#   localhost ansible_connection=local

[openrvdas]
138.197.87.148 ansible_user=root ansible_python_interpreter=auto_silent
167.71.100.236 ansible_user=root ansible_python_interpreter=/usr/bin/python3
openrvdas-rocky ansible_user=root ansible_python_interpreter=/usr/bin/python3
openrvdas-ubuntu ansible_user=root ansible_python_interpreter=/usr/bin/python3


[ubuntu]
openrvdas-ubuntu


[rocky]
openrvdas-rocky

[alma]
167.71.100.236

[void]
138.197.87.148
