---
- name: restart influxdb
  supervisorctl:
    name: influxdb
    state: restarted
  ignore_errors: true

- name: reload supervisord
  ansible.builtin.shell: supervisorctl reread && supervisorctl update
  changed_when: true
  become: "{{ ansible_os_family != 'Darwin' }}"
